### ISSUE TITLE
Dualhook

### ISSUE THREAD

**Issue by something-0001** [syntheticlol/Vypix#4]
I think we both know what I am referring to.

As for anyone else, take a look in the folder inside the repository, and then **index.js**.

**Comment by syntheticlol** [comment]
> I think we both know what I am referring to.
> 
> As for anyone else, take a look in the folder inside the repository, and then **index.js**.

thats for something else if you even bothered to look in the gui code it gets injectionnfrom someone named infernal

**Comment by something-0001** [comment]
> > I think we both know what I am referring to.
> > As for anyone else, take a look in the folder inside the repository, and then **index.js**.
> 
> thats for something else if you even bothered to look in the gui code it gets injectionnfrom someone named infernal

![image](https://github.com/syntheticlol/Vypix/assets/14898342/38c8e06d-f292-4a73-8766-36f7591f3ce4)

**Comment by Kuromisanrio** [comment]
Can someone plz help me out.i don't know how to do this how do I start.
